Repository softeerbootcamp-6th/Team1-ImSnacks, pull requests merged in 2025-07, with the labels that each got.

#5 [FEAT] 프로젝트 세팅
  frontend/.gitignore
  frontend/.prettierrc
  frontend/README.md
  frontend/eslint.config.js
  frontend/index.html
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/App.tsx
  frontend/src/main.tsx
  frontend/src/vite-env.d.ts
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
Labels: 🙌🏻 Setting, 🖼️ FE

#8 [Feat] PR 병합 시 브랜치명에 따라 자동으로 이슈를 닫는 workflow 추가
  .github/workflows/close-issues-on-merge.yml
  frontend/.gitignore
  frontend/.prettierrc
  frontend/README.md
  frontend/eslint.config.js
  frontend/index.html
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/App.tsx
  frontend/src/main.tsx
  frontend/src/vite-env.d.ts
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
Labels: 🧹 Chore, 🙌🏻 Setting

#10 [Feat] NavBar 제작 및 라우팅 기능 구현
  frontend/src/App.tsx
  frontend/src/layouts/Layout.tsx
  frontend/src/layouts/navBar/NavBar.tsx
  frontend/src/main.tsx
  frontend/src/routes/Router.tsx
Labels: ✨ Feature, 🖼️ FE

#11 [Feat] 디자인 시스템 구축
  frontend/public/assets/fonts/SUITE-Variable.ttf
  frontend/src/App.tsx
  frontend/src/layouts/Layout.tsx
  frontend/src/pages/HomePage.tsx
  frontend/src/routes/Router.tsx
  frontend/src/styles/GlobalStyles.tsx
  frontend/src/styles/borderRadius.ts
  frontend/src/styles/colors.ts
  frontend/src/styles/effects.ts
  frontend/src/styles/gradientStyles.ts
  frontend/src/styles/typography.ts
Labels: 🙌🏻 Setting, 🖼️ FE

#12 [Feat] 디자인 시스템 구현: spacing, weatherboard gradient, dropshadow 추가
  frontend/src/routes/Router.tsx
  frontend/src/styles/colors.ts
  frontend/src/styles/effects.ts
  frontend/src/styles/spacing.ts
Labels: 🙌🏻 Setting, 🖼️ FE

#37 [FIX] CD 워크플로우 경로 수정 및 ec2 username 변경
  .github/workflows/CD.yml
Labels: 🛠️ Fix, 🌏 Infra
