Repository softeerbootcamp-6th/Team1-ImSnacks, pull requests merged in 2025-08, with the labels that each got.

#72 [Feat] PR 생성 시 status 변경 자동화
  .github/workflows/auto-issue-column-transition.yml
Labels: ✨ Feature

#75 feat: Epic 이슈 템플릿 추가
  .github/ISSUE_TEMPLATE/epic.yml
Labels: ✨ Feature

#70 [Feat] 테스트 커버리지 체크를 위한 jacoco 라이브러리 적용
  .github/workflows/backend-ci.yml
  backend/build.gradle
Labels: ✨ Feature, 🗃️ BE

#66 [Fix] 빌드 에러 수정 - tsconfig.node.json, xmls수정
  frontend/src/assets/iconComponents/Cloudy.tsx
  frontend/src/assets/iconComponents/CloudyNight.tsx
  frontend/src/assets/iconComponents/HeavyRain.tsx
  frontend/src/assets/iconComponents/LessCloudy.tsx
  frontend/src/assets/iconComponents/Night.tsx
  frontend/src/assets/iconComponents/Rain.tsx
  frontend/src/assets/iconComponents/Snow.tsx
  frontend/src/assets/iconComponents/Sunny.tsx
  frontend/src/assets/iconComponents/Thunder.tsx
  frontend/src/assets/iconComponents/Wind.tsx
  frontend/src/components/toolTip/ToolTip.tsx
  frontend/src/constants/flatIcons.ts
  frontend/src/pages/homePage/HomePage.style.ts
  frontend/src/pages/homePage/HomePage.tsx
  frontend/src/pages/homePage/components/btnSelectChip/BtnSelectChip.style.ts
  frontend/src/pages/homePage/components/btnSelectChip/BtnSelectChip.tsx
  frontend/src/pages/homePage/components/graphMenu/GraphMenu.style.ts
  frontend/src/pages/homePage/components/graphMenu/GraphMenu.tsx
  frontend/src/pages/homePage/components/graphMenuTab/GraphMenuTab.style.ts
  frontend/src/pages/homePage/components/graphMenuTab/GraphMenuTab.tsx
  frontend/src/pages/homePage/components/headLine/HeadLine.style.ts
  frontend/src/pages/homePage/components/headLine/HeadLine.tsx
  frontend/src/pages/homePage/components/mainPageGraph/MainPageGraph.style.ts
  frontend/src/pages/homePage/components/mainPageGraph/MainPageGraph.tsx
  frontend/src/pages/homePage/components/workCell/WorkCell.style.ts
  frontend/src/pages/homePage/components/workCell/WorkCell.tsx
  frontend/src/pages/homePage/components/workContainer/WorkContainer.tsx
  frontend/src/pages/myFarmPage/components/cropInfoCard/CropInfoCard.style.ts
  frontend/src/pages/myFarmPage/components/cropInfoCard/CropInfoCard.tsx
  frontend/src/types/btnSelectChip.type.ts
  frontend/src/types/workCell.type.ts
  frontend/tsconfig.node.json
Labels: 🛠️ Fix, 🖼️ FE

#80 [Fix] WeatherRisk 불필요한 setter 삭제
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/writer/WeatherWriter.java
Labels: 🛠️ Fix

#83 [Feat] 날씨 정보 페이지 컴포넌트 분리 및 구조화, commonStyles 생성
  frontend/src/pages/weatherBoardPage/WeatherBoardPage.style.ts
  frontend/src/pages/weatherBoardPage/WeatherBoardPage.tsx
  frontend/src/pages/weatherBoardPage/components/weatherBoardDust/WeatherBoardDust.tsx
  frontend/src/pages/weatherBoardPage/components/weatherBoardHumidity/WeatherBoardHumidity.tsx
  frontend/src/pages/weatherBoardPage/components/weatherBoardRain/WeatherBoardRain.tsx
  frontend/src/pages/weatherBoardPage/components/weatherBoardSunset/WeatherBoardSunset.tsx
  frontend/src/pages/weatherBoardPage/components/weatherBoardTemperature/WeatherBoardTemparature.tsx
  frontend/src/pages/weatherBoardPage/components/weatherBoardUV/WeatherBoardUV.tsx
  frontend/src/pages/weatherBoardPage/components/weatherBoardWeekly/WeatherBoardWeekly.tsx
  frontend/src/pages/weatherBoardPage/components/weatherBoardWind/WeatherBoardWind.tsx
  frontend/src/routes/Router.tsx
  frontend/src/styles/commonStyles.ts
  frontend/src/styles/effects.ts
Labels: ✨ Feature, 🧹 Chore, 🖼️ FE

#91 [Feat] husky 세팅 및 pre-push 시 lint 실행 스크립트 추가
  .husky/pre-push
  frontend/package.json
  frontend/pnpm-lock.yaml
Labels: ✅ Test, 🙌🏻 Setting, 🖼️ FE

#84 [Feat] 공통 툴팁 컴포넌트 개발
  .github/workflows/auto-issue-column-transition.yml
  frontend/src/assets/icons/flat/Arrow.svg
  frontend/src/components/toolTip/ToolTip.style.ts
  frontend/src/components/toolTip/ToolTip.tsx
  frontend/src/hooks/useVisibility.ts
  frontend/src/layouts/navBar/NavBar.styles.ts
  frontend/src/layouts/navBar/NavBar.tsx
  frontend/src/pages/myFarmPage/components/myCropInfo/MyCropInfo.tsx
  frontend/src/pages/myFarmPage/components/myFarmHeader/MyFarmHeader.style.ts
  frontend/src/pages/myFarmPage/components/myFarmHeader/MyFarmHeader.tsx
  frontend/src/styles/customBorderGradientStyles.ts
  frontend/src/styles/gradientStyles.ts
  frontend/src/types/tooltip.type.ts
Labels: ✨ Feature, 🖼️ FE

#81 [Feat] Proccesor 로직 중 open api response를 entity에 매핑하는 로직 구현
  .github/ISSUE_TEMPLATE/epic.yml
  .github/workflows/auto-issue-column-transition.yml
  .github/workflows/backend-ci.yml
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/dto/VilageFcstResponse.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/processor/WeatherProcessor.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/utils/ForecastTimeUtils.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/writer/dto/ShortTermWeatherDto.java
  batch/src/test/java/com/ImSnacks/NyeoreumnagiBatch/ForecastTimeUtilsTest.java
  batch/src/test/java/com/ImSnacks/NyeoreumnagiBatch/WeatherProcessorTest.java
  batch/src/test/java/com/ImSnacks/NyeoreumnagiBatch/WeatherWriterTest.java
Labels: ✨ Feature, 🗃️ BE

#106 [Feat] Batch 서버 현재 시간으로 JobParameters 생성
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/utils/params/WeatherJobParams.java
  batch/src/test/java/com/ImSnacks/NyeoreumnagiBatch/ApiCallerTest.java
  batch/src/test/java/com/ImSnacks/NyeoreumnagiBatch/ForecastTimeUtilsTest.java
  batch/src/test/java/com/ImSnacks/NyeoreumnagiBatch/WeatherJobParamsTest.java
Labels: ✨ Feature, 🗃️ BE

#108 [Feat] 배치 job에 scheduler 적용
  .gitignore
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/WeatherJobScheduler.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/processor/WeatherProcessor.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/processor/utils/ForecastTimeUtils.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/processor/utils/weatherRiskFilter/RainFilter.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/processor/utils/weatherRiskFilter/TemperatureFilter.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/processor/utils/weatherRiskFilter/WeatherRiskFilter.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/processor/utils/weatherRiskFilter/WindFilter.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/reader/WeatherReader.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/utils/params/WeatherJobParams.java
  batch/src/main/resources/application.yml
  batch/src/test/java/com/ImSnacks/NyeoreumnagiBatch/ForecastTimeUtilsTest.java
  batch/src/test/java/com/ImSnacks/NyeoreumnagiBatch/filterTest/RainFilterTest.java
  batch/src/test/java/com/ImSnacks/NyeoreumnagiBatch/filterTest/TemperatureFilterTest.java
  batch/src/test/java/com/ImSnacks/NyeoreumnagiBatch/filterTest/WindFilterTest.java
Labels: ✨ Feature, 🗃️ BE

#111 [Feat] Custom ApiResponse 구현
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/CustomResponseBody.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/ResponseUtil.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/StatusCode.java
Labels: ✨ Feature, 🗃️ BE

#112 [Feat] 프론트엔드 배포 cd 파일
  .github/workflows/frontend-cd.yml
Labels: 🌏 Infra, 🖼️ FE

#116 [Feat] Member entity 추가
  backend/build.gradle
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/member/entity/Member.java
  backend/src/main/resources/application.yml
Labels: ✨ Feature, 🗃️ BE

#118 [Feat] 사용자 인증/인가를 위한 JWT 토큰 관련 기능 및 interceptor 구현
  backend/build.gradle
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/annotation/PreAuthorize.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/argumentResolver/JwtAuthHandlerArgumentResolver.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/exception/AuthResponseStatus.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/exception/JwtException.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/interceptor/JwtAuthInterceptor.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/jwt/AuthTokens.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/jwt/JwtProvider.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/config/WebConfig.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/NyeoreumnagiApplicationTests.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/authTest/JwtAuthHandlerArgumentResolverTest.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/authTest/JwtAuthInterceptorTest.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/authTest/JwtProviderTest.java
Labels: ✨ Feature, 🗃️ BE

#123 [Fix] 환경 변수 추가로 인한 CD action 오류 해결
  .github/workflows/CD.yml
  backend/.deploy/nyeoreumnagi-blue-deploy.yml
  backend/.deploy/nyeoreumnagi-green-deploy.yml
Labels: 🛠️ Fix, 🗃️ BE

#124 [Hotfix] docker compose에서 환경변수 잘못 넣은 오류 해결
  backend/.deploy/nyeoreumnagi-blue-deploy.yml
  backend/.deploy/nyeoreumnagi-green-deploy.yml
Labels: 🛠️ Fix, 🗃️ BE

#125 [Feat] 농작업 등록 기능 구현 및 Swagger 세팅
  backend/build.gradle
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/CustomResponseBody.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/GlobalExceptionHandler.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/ResponseUtil.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/StatusCode.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/config/SwaggerConfig.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/config/WebConfig.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/util/TimeValidator.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/member/entity/Member.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/member/exception/MemberException.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/member/exception/MemberResponseStatus.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/member/repository/MemberRepository.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/my_work/entity/MyWork.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/controller/MyWorkController.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/dto/request/ResisterMyWorkRequest.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/dto/response/ResisterMyWorkResponse.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/entity/Crop.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/entity/LifeCycle.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/entity/LifeCycleAndRecommendedWork.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/entity/LifeCycleAndRecommendedWorkId.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/entity/LifeCyclePeriod.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/entity/MyCrop.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/entity/MyWork.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/entity/RecommendedWork.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/entity/WorkStatus.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/exception/WorkException.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/exception/WorkResponseStatus.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/repository/MyCropRepository.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/repository/MyWorkRepository.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/repository/RecommendedWorkRepository.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/service/MyWorkService.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/work/entity/MyWorkTest.java
Labels: ✨ Feature, 🗃️ BE

#127 [Feat] 농작업 삭제 및 Swagger 에서 memberId 파라미터 숨김 처리
  .github/workflows/CD.yml
  backend/.deploy/Dockerfile
  backend/build.gradle
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/GlobalExceptionHandler.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/config/SwaggerConfig.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/config/WebConfig.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/member/entity/Member.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/controller/MyWorkController.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/dto/request/DeleteMyWorkRequest.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/dto/request/ResisterMyWorkRequest.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/exception/WorkResponseStatus.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/service/MyWorkService.java
  backend/src/main/resources/application.yml
Labels: ✨ Feature, 🗃️ BE

#130 [Feat] 드래그앤드랍 훅 구현, 수정 및 삭제
  frontend/src/constants/cropName.ts
  frontend/src/constants/workScheduleData.ts
  frontend/src/hooks/dnd/useDragAndDrop.ts
  frontend/src/hooks/dnd/useRemoveOnOutOfBound.ts
  frontend/src/pages/homePage/components/workCardRegister/WorkCardRegister.style.ts
  frontend/src/pages/homePage/components/workCardRegister/WorkCardRegister.tsx
  frontend/src/pages/homePage/components/workCell/WorkCell.style.ts
  frontend/src/pages/homePage/components/workCell/WorkCell.tsx
  frontend/src/pages/homePage/components/workCellsContainer/WorkCellsContainer.tsx
  frontend/src/pages/homePage/components/workContainer/WorkContainer.tsx
  frontend/src/pages/homePage/utils/getInitialWorkBlocks.ts
  frontend/src/pages/homePage/utils/updateBlockWorkTime.ts
  frontend/src/pages/myFarmPage/components/workCardWeb/WorkCardWeb.tsx
  frontend/src/types/workCard.type.ts
Labels: ✨ Feature, 🖼️ FE

#133 Feat: 날씨 정보 페이지 - 7일 날씨 UI 구현
  frontend/src/pages/weatherBoardPage/components/temperatureDot/TemperatureDot.tsx
  frontend/src/pages/weatherBoardPage/components/weatherBoardTemperature/WeatherBoardTemperature.tsx
  frontend/src/pages/weatherBoardPage/components/weatherBoardWeekly/WeatherBoardWeekly.style.ts
  frontend/src/pages/weatherBoardPage/components/weatherBoardWeekly/WeatherBoardWeekly.tsx
  frontend/src/pages/weatherBoardPage/components/weeklyContent/WeeklyContent.style.tsx
  frontend/src/pages/weatherBoardPage/components/weeklyContent/WeeklyContent.tsx
Labels: ✨ Feature, 🖼️ FE

#134 [Release] FE v1.0.0
  frontend/src/constants/cropName.ts
  frontend/src/constants/flatIcons.ts
  frontend/src/constants/workScheduleData.ts
  frontend/src/hooks/dnd/useDragAndDrop.ts
  frontend/src/hooks/dnd/useRemoveOnOutOfBound.ts
  frontend/src/pages/homePage/components/graphMenuTab/GraphMenuTab.tsx
  frontend/src/pages/homePage/components/workCardRegister/WorkCardRegister.style.ts
  frontend/src/pages/homePage/components/workCardRegister/WorkCardRegister.tsx
  frontend/src/pages/homePage/components/workCell/WorkCell.style.ts
  frontend/src/pages/homePage/components/workCell/WorkCell.tsx
  frontend/src/pages/homePage/components/workCellsContainer/WorkCellsContainer.tsx
  frontend/src/pages/homePage/components/workContainer/WorkContainer.tsx
  frontend/src/pages/homePage/utils/getInitialWorkBlocks.ts
  frontend/src/pages/homePage/utils/updateBlockWorkTime.ts
  frontend/src/pages/myFarmPage/components/workCardWeb/WorkCardWeb.tsx
  frontend/src/pages/weatherBoardPage/WeatherBoardPage.tsx
  frontend/src/pages/weatherBoardPage/components/temperatureDot/TemperatureDot.tsx
  frontend/src/pages/weatherBoardPage/components/weatherBoardTemperature/WeatherBoardTemparature.tsx
  frontend/src/pages/weatherBoardPage/components/weatherBoardTemperature/WeatherBoardTemperature.style.ts
  frontend/src/pages/weatherBoardPage/components/weatherBoardTemperature/WeatherBoardTemperature.tsx
  frontend/src/pages/weatherBoardPage/components/weatherBoardWeekly/WeatherBoardWeekly.style.ts
  frontend/src/pages/weatherBoardPage/components/weatherBoardWeekly/WeatherBoardWeekly.tsx
  frontend/src/pages/weatherBoardPage/components/weeklyContent/WeeklyContent.style.tsx
  frontend/src/pages/weatherBoardPage/components/weeklyContent/WeeklyContent.tsx
  frontend/src/pages/weatherBoardPage/utils/weeklyTemperatureUtil.ts
  frontend/src/types/weather.types.ts
  frontend/src/types/workCard.type.ts
Labels: 🖼️ FE, Release

#129 [Fix] MyWork에 저장하는 시간 타입을 String("HHmm") 에서 LocalDateTime으로 변경
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/util/TimeValidator.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/dto/request/ResisterMyWorkRequest.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/entity/MyWork.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/work/entity/MyWorkTest.java
Labels: 🛠️ Fix, 🗃️ BE

#142 [Fix] Member의 refreshToken 데이터 타입을 binary(16) -> VARCHAR(36)으로 변경
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/member/entity/Member.java
Labels: 🛠️ Fix, 🗃️ BE

#139 [fix] 프론트엔드 cd pnpm 설치 에러 수정, 시크릿 키 테스트용 코드 추가
  .github/workflows/frontend-cd.yml
Labels: 🛠️ Fix, 🌏 Infra, 🙌🏻 Setting, 🖼️ FE

#131 [Feat] 농작업 시간 수정 기능
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/GlobalExceptionHandler.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/response/CustomResponseBody.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/response/ResponseUtil.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/response/StatusCode.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/util/TimeValidator.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/controller/MyWorkController.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/dto/request/DeleteMyWorkRequest.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/dto/request/ModifyMyWorkRequest.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/dto/request/RegisterMyWorkRequest.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/dto/request/ResisterMyWorkRequest.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/dto/response/ModifyMyWorkResponse.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/entity/MyWork.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/service/MyWorkService.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/common/util/TimeValidatorTest.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/work/entity/MyWorkTest.java
Labels: ✨ Feature, ✅ Test, 🗃️ BE

#152 [Fix] be 브랜치에서 fe 작업 삭제
  frontend/custom.d 2.ts
  frontend/src/constants/cropIcons 2.ts
  frontend/src/constants/cropLifeCycle 2.ts
  frontend/src/constants/cropName 2.ts
  frontend/src/constants/crops 2.ts
  frontend/src/constants/flatIcons 2.ts
  frontend/src/constants/graphMenu 2.ts
  frontend/src/constants/workScheduleData 2.ts
  frontend/src/hooks/useVisibility 2.ts
  frontend/src/hooks/useWeeklyCalendar 2.ts
  frontend/src/layouts/Layout 2.tsx
  frontend/src/routes/Router 2.tsx
  frontend/src/styles/GlobalStyles 2.tsx
  frontend/src/styles/borderRadius 2.ts
  frontend/src/styles/colors 2.ts
  frontend/src/styles/commonStyles 2.ts
  frontend/src/styles/customBorderGradientStyles 2.ts
  frontend/src/styles/effects 2.ts
  frontend/src/styles/gradientStyles 2.ts
  frontend/src/styles/spacing 2.ts
  frontend/src/styles/typography 2.ts
  frontend/src/types/btnSelectChip.type 2.ts
  frontend/src/types/crop.type 2.ts
  frontend/src/types/cropInfoCard.type 2.ts
  frontend/src/types/mainGraph.type 2.ts
  frontend/src/types/tooltip.type 2.ts
  frontend/src/types/weather.types 2.ts
  frontend/src/types/workCard.type 2.ts
  frontend/src/types/workCell.type 2.ts
  frontend/src/types/workChip.type 2.ts
  frontend/src/utils/converHexToRGBA 2.ts
  frontend/src/utils/getUnit 2.ts
  frontend/src/utils/groupDataRecord 2.ts
  frontend/src/utils/koreanParticleUtil 2.ts
Labels: 🛠️ Fix, 🗃️ BE

#140 [Fix] 농작업 삭제 요청 시 status가 `COMPLETE` 이면 실패하도록 변경
  backend/build.gradle
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/entity/LifeCycleAndRecommendedWorkId.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/entity/MyWork.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/exception/WorkResponseStatus.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/service/MyWorkService.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/work/entity/MyWorkTest.java
Labels: 🛠️ Fix, ✅ Test, 🗃️ BE

#157 [Docs] GitHub Discussion 용 템플릿 추가
  .github/DISCUSSION_TEMPLATE/공지.yml
  .github/DISCUSSION_TEMPLATE/논의 공간.yml
  .github/DISCUSSION_TEMPLATE/아이디어.yml
  .github/DISCUSSION_TEMPLATE/투표.yml
Labels: 📃 Docs

#162 fix: GitHub Discussion 템플릿명 영어로 수정
  .github/DISCUSSION_TEMPLATE/Discussion.yml
  .github/DISCUSSION_TEMPLATE/Idea.yml
  .github/DISCUSSION_TEMPLATE/Notice.yml
  .github/DISCUSSION_TEMPLATE/Poll.yml
Labels: 📃 Docs

#164 fix: description 을 큰따옴표로 묶음
  .github/DISCUSSION_TEMPLATE/공지.yml
  .github/DISCUSSION_TEMPLATE/논의 공간.yml
  .github/DISCUSSION_TEMPLATE/아이디어.yml
  .github/DISCUSSION_TEMPLATE/투표.yml
Labels: 🛠️ Fix, 📃 Docs

#167 fix: 템플릿 카테고리를 영어로 다시 변경
  .github/DISCUSSION_TEMPLATE/Discussion.yml
  .github/DISCUSSION_TEMPLATE/Idea.yml
  .github/DISCUSSION_TEMPLATE/Notice.yml
  .github/DISCUSSION_TEMPLATE/Poll.yml
Labels: 🛠️ Fix, 📃 Docs

#169 [Feat] 날씨 정보 페이지 - 일일 최고 자외선 UI 구현
  frontend/src/pages/weatherBoardPage/WeatherBoardPage.style.ts
  frontend/src/pages/weatherBoardPage/WeatherBoardPage.tsx
  frontend/src/pages/weatherBoardPage/components/weatherBoardTemperature/WeatherBoardTemperature.style.ts
  frontend/src/pages/weatherBoardPage/components/weatherBoardTemperature/WeatherBoardTemperature.tsx
  frontend/src/pages/weatherBoardPage/components/weatherBoardUV/WeatherBoardUV.style.ts
  frontend/src/pages/weatherBoardPage/components/weatherBoardUV/WeatherBoardUV.tsx
  frontend/src/pages/weatherBoardPage/utils/uvUtil.ts
Labels: ✨ Feature, 🔨 Refactor, 🧹 Chore, 🖼️ FE

#154 [Fix] WeatherRisk에 nx, ny, jobExecutionId 담기
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/processor/WeatherProcessor.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/processor/dto/VilageFcstItemsDto.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/processor/utils/ForecastTimeUtils.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/processor/utils/weatherRiskFilter/RainFilter.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/processor/utils/weatherRiskFilter/TemperatureFilter.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/processor/utils/weatherRiskFilter/WeatherRiskFilter.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/processor/utils/weatherRiskFilter/WindFilter.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/writer/WeatherWriter.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/writer/dto/ShortTermWeatherDto.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/writer/entity/WeatherRisk.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/writer/repository/ShortTermWeatherForecastRepository.java
  batch/src/main/resources/application.yml
  batch/src/test/java/com/ImSnacks/NyeoreumnagiBatch/ForecastTimeUtilsTest.java
  batch/src/test/java/com/ImSnacks/NyeoreumnagiBatch/WeatherProcessorTest.java
  batch/src/test/java/com/ImSnacks/NyeoreumnagiBatch/WeatherWriterTest.java
  batch/src/test/java/com/ImSnacks/NyeoreumnagiBatch/filterTest/RainFilterTest.java
  batch/src/test/java/com/ImSnacks/NyeoreumnagiBatch/filterTest/TemperatureFilterTest.java
  batch/src/test/java/com/ImSnacks/NyeoreumnagiBatch/filterTest/WindFilterTest.java
Labels: 🛠️ Fix, 🗃️ BE

#168 [Feat] 홈페이지 날씨 리스크 반환 API 구현
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/config/WebConfig.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/enums/WeatherRiskType.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/controller/WeatherController.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/dto/response/GetFcstRiskResponse.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/entity/WeatherRisk.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/repository/WeatherRiskRepository.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/LinePoint.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/WeatherService.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/util/WeatherRiskIntervalMerger.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/weather/WeatherServiceTest.java
Labels: ✨ Feature, 🗃️ BE

#180 [Feat] 날씨 정보 페이지 - 일출/일몰 컴포넌트 UI 구현
  frontend/src/assets/icons/flat/SunEffect.svg
  frontend/src/assets/icons/flat/index.ts
  frontend/src/pages/weatherBoardPage/WeatherBoardPage.tsx
  frontend/src/pages/weatherBoardPage/components/weatherBoardSunset/WeatherBoardSunset.style.ts
  frontend/src/pages/weatherBoardPage/components/weatherBoardSunset/WeatherBoardSunset.tsx
  frontend/src/pages/weatherBoardPage/hooks/useSunsetAnimation.ts
  frontend/src/pages/weatherBoardPage/utils/sunsetUtil.ts
Labels: ✨ Feature, 🖼️ FE

#182 [Fix] 드래그 시 시간 업데이트가 제대로 되지 않는 오류 해결
  frontend/src/pages/homePage/components/workContainer/WorkContainer.tsx
  frontend/src/pages/homePage/utils/updateBlockWorkTime.ts
Labels: 🛠️ Fix, 🖼️ FE

#189 [Feat] 홈페이지/모바일 기상 요약 조회 API 구현
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/GlobalExceptionHandler.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/enums/WeatherCondition.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/controller/WeatherController.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/dto/response/GetWeatherConditionResponse.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/entity/DashboardTodayWeather.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/entity/DashboardTodayWeatherId.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/entity/ShortTermWeatherForecast.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/entity/WeatherRisk.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/exception/WeatherResponseStatus.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/repository/DashboardTodayWeatherRepository.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/SunriseSunSetTime.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/WeatherService.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/weather/WeatherServiceTest.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/weather/entity/ShortTermWeatherForecastTest.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/processor/WeatherProcessor.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/reader/WeatherReader.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/writer/WeatherWriter.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/writer/dto/ShortTermWeatherDto.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/writer/entity/ShortTermWeatherForecast.java
Labels: ✨ Feature, 🗃️ BE

#190 [Feat] 컨테이너 외부 드래그 방지 및 삭제 버튼 연동
  frontend/src/components/dnd/DragOverlay.style.ts
  frontend/src/constants/workScheduleData.ts
  frontend/src/hooks/dnd/useRemoveOnOutOfBound.ts
  frontend/src/hooks/dnd/useRevertPosition.ts
  frontend/src/pages/homePage/components/workCardRegister/WorkCardRegister.style.ts
  frontend/src/pages/homePage/components/workCardRegister/WorkCardRegister.tsx
  frontend/src/pages/homePage/components/workContainer/WorkContainer.tsx
  frontend/src/pages/homePage/utils/animateBlock.ts
  frontend/src/pages/myFarmPage/components/workCardWeb/WorkCardWeb.tsx
  frontend/src/types/workCard.type.ts
Labels: ✨ Feature, 🖼️ FE

#200 [Feat] 작업 시간 변경 (리사이즈) 기능 구현
  .github/workflows/frontend-ci.yml
  frontend/src/pages/homePage/HomePage.tsx
  frontend/src/pages/homePage/components/workCardRegister/WorkCardRegister.style.ts
  frontend/src/pages/homePage/components/workCardRegister/WorkCardRegister.tsx
  frontend/src/pages/homePage/components/workContainer/WorkContainer.tsx
  frontend/src/pages/homePage/hooks/useResize.ts
Labels: ✨ Feature, 🖼️ FE

#206 [Release] fix frontend cd yml
  .github/workflows/frontend-cd.yml
Labels: 🛠️ Fix, 🖼️ FE, Release

#207 [Fix] frontend-cd workflow id-token permission 추가
  .github/workflows/frontend-cd.yml
Labels: 🛠️ Fix, 🖼️ FE, Release

#213 [Feat] dnd 충돌 감지 및 충돌 시 겹치지 않는 위치로 이동
  frontend/src/constants/workScheduleData.ts
  frontend/src/contexts/useWorkBlocks.ts
  frontend/src/hooks/dnd/useRevertPosition.ts
  frontend/src/hooks/useResizeCollision.ts
  frontend/src/pages/homePage/components/registerWorkContainer/RegisterWorkContainer.tsx
  frontend/src/pages/homePage/components/workCardRegister/WorkCardRegister.style.ts
  frontend/src/pages/homePage/components/workCardRegister/WorkCardRegister.tsx
  frontend/src/pages/homePage/components/workCardRegisterContent/WorkCardRegisterContent.style.ts
  frontend/src/pages/homePage/components/workCardRegisterContent/WorkCardRegisterContent.tsx
  frontend/src/pages/homePage/components/workContainer/WorkContainer.tsx
  frontend/src/pages/homePage/hooks/useChangeTimeByResize.ts
  frontend/src/pages/homePage/utils/getInitialWorkBlocks.ts
  frontend/src/types/workCard.type.ts
  frontend/src/utils/animateBlock.ts
  frontend/src/utils/collisionUtils.ts
Labels: ✨ Feature, 🖼️ FE

#219 [Fix] CI 오류 수정
  .github/workflows/backend-ci.yml
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/lifecycle/LifeCycleResolver.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/lifecycle/entity/LifeCycle.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/repository/LifeCycleRepository.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/service/RecommendedWorkService.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/lifecycle/LifeCycleResolverTest.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/weather/util/WorkScheduleCalculatorTest.java
Labels: 🛠️ Fix, 🗃️ BE

#195 [Feat] 기상 브리핑 API
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/controller/WeatherController.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/dto/response/GetFcstRisk.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/dto/response/GetWeatherBriefing.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/dto/response/GetWeatherCondition.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/dto/response/GetWeatherGraph.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/entity/WeatherRisk.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/Briefing.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/WeatherService.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/util/WeatherRiskIntervalMerger.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/repository/LifeCycleRepository.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/service/RecommendedWorkService.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/weather/WeatherBriefingTest.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/weather/WeatherServiceTest.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/weather/util/WorkScheduleCalculatorTest.java
Labels: ✨ Feature, 🗃️ BE

#225 [Feat] CORS 허용을 위한 메소드 추가
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/config/WebConfig.java
Labels: ✨ Feature, 🗃️ BE

#227 [Release] FE v1.0.2 - 퍼블리싱 완성물 dev merge
  .github/workflows/frontend-cd.yml
  frontend/src/assets/icons/flat/LeftArrowCircleBtn.svg
  frontend/src/assets/icons/flat/RightArrowCircleBtn.svg
  frontend/src/assets/icons/flat/index.ts
  frontend/src/assets/images/pestDemage/Bugs.svg
  frontend/src/assets/images/pestDemage/Germs.svg
  frontend/src/assets/images/weatherDemage/FlowerDrop.svg
  frontend/src/assets/images/weatherDemage/FruitCracking.svg
  frontend/src/assets/images/weatherDemage/FruitCraking.svg
  frontend/src/assets/images/weatherDemage/FruitDrop.svg
  frontend/src/assets/images/weatherDemage/PoorColoring.svg
  frontend/src/assets/images/weatherDemage/SunBrun.svg
  frontend/src/assets/images/weatherDemage/Sunburn.svg
  frontend/src/assets/images/weatherDemage/WaterDefficieny.svg
  frontend/src/assets/images/weatherDemage/WaterDeficiency.svg
  frontend/src/assets/images/weatherDemage/index.ts
  frontend/src/constants/damageGraphic.ts
  frontend/src/constants/workScheduleData.ts
  frontend/src/contexts/useWorkBlocks.ts
  frontend/src/hooks/dnd/useRevertPosition.ts
  frontend/src/hooks/handleClickOutside.ts
  frontend/src/hooks/useResizeCollision.ts
  frontend/src/pages/homePage/components/btnSelectChip/BtnSelectChip.style.ts
  frontend/src/pages/homePage/components/btnSelectChip/BtnSelectChip.tsx
  frontend/src/pages/homePage/components/damageCard/DamageCard.style.ts
  frontend/src/pages/homePage/components/damageCard/DamageCard.tsx
  frontend/src/pages/homePage/components/damageInfoCard/DamageInfoCard.style.ts
  frontend/src/pages/homePage/components/damageInfoCard/DamageInfoCard.tsx
  frontend/src/pages/homePage/components/damagePestArrowButton/DamagePestArrowButton.style.ts
  frontend/src/pages/homePage/components/damagePestArrowButton/DamagePestArrowButton.tsx
  frontend/src/pages/homePage/components/damagePests/DamagePests.style.ts
  frontend/src/pages/homePage/components/damagePests/DamagePests.tsx
  frontend/src/pages/homePage/components/mainLineChart/MainLineChart.tsx
  frontend/src/pages/homePage/components/registerWorkContainer/RegisterWorkContainer.tsx
  frontend/src/pages/homePage/components/workCardRegister/WorkCardRegister.style.ts
  frontend/src/pages/homePage/components/workCardRegister/WorkCardRegister.tsx
  frontend/src/pages/homePage/components/workCardRegisterContent/WorkCardRegisterContent.style.ts
  frontend/src/pages/homePage/components/workCardRegisterContent/WorkCardRegisterContent.tsx
  frontend/src/pages/homePage/components/workContainer/WorkContainer.tsx
  frontend/src/pages/homePage/desktop/DesktopHomePage.style.ts
  frontend/src/pages/homePage/desktop/DesktopHomePage.tsx
  frontend/src/pages/homePage/hooks/useChangeTimeByResize.ts
  frontend/src/pages/homePage/utils/damagePestsUtil.ts
  frontend/src/pages/homePage/utils/getInitialWorkBlocks.ts
  frontend/src/pages/homePage/utils/lineChartUtil.ts
  frontend/src/types/damage.type.ts
  frontend/src/types/workCard.type.ts
  frontend/src/utils/animateBlock.ts
  frontend/src/utils/collisionUtils.ts
Labels: 🖼️ FE, Release

#233 [Fix] `DELETE`, `OPTIONS` 에서 cors 정책이 적용되는 문제 해결
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/config/WebConfig.java
Labels: 🛠️ Fix, 🗃️ BE

#234 [Feat] 일출몰 시각 조회 API 구현
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/controller/WeatherController.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/dto/response/GetFcstRiskResponse.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/dto/response/GetSunRiseSetTimeResponse.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/dto/response/GetWeatherBriefing.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/dto/response/GetWeatherBriefingResponse.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/dto/response/GetWeatherConditionResponse.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/dto/response/GetWeatherGraphResponse.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/exception/WeatherResponseStatus.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/repository/DashboardTodayWeatherRepository.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/WeatherService.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/util/WeatherRiskIntervalMerger.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/weather/WeatherBriefingTest.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/weather/WeatherServiceTest.java
Labels: ✨ Feature, 🗃️ BE

#250 [Feat] openapi-generator-cli로 dto 타입 자동 생성 구축 #231
  frontend/.prettierignore
  frontend/eslint.config.js
  frontend/generate_openapi_types.sh
  frontend/openapitools.json
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/apis/http.ts
  frontend/src/apis/myWork.api.ts
  frontend/src/apis/weather.api.ts
  frontend/src/types/openapiGenerator/index.ts
  frontend/src/types/openapiGenerator/models/AuthTokens.ts
  frontend/src/types/openapiGenerator/models/CustomResponseBodyAuthTokens.ts
  frontend/src/types/openapiGenerator/models/CustomResponseBodyGetFcstRisk.ts
  frontend/src/types/openapiGenerator/models/CustomResponseBodyGetWeatherBriefing.ts
  frontend/src/types/openapiGenerator/models/CustomResponseBodyGetWeatherCondition.ts
  frontend/src/types/openapiGenerator/models/CustomResponseBodyGetWeatherGraph.ts
  frontend/src/types/openapiGenerator/models/CustomResponseBodyListGetMyWorksOfTodayResponse.ts
  frontend/src/types/openapiGenerator/models/CustomResponseBodyModifyMyWorkResponse.ts
  frontend/src/types/openapiGenerator/models/CustomResponseBodyRecommendWorksResponse.ts
  frontend/src/types/openapiGenerator/models/CustomResponseBodyRegisterMyWorkResponse.ts
  frontend/src/types/openapiGenerator/models/CustomResponseBodyVoid.ts
  frontend/src/types/openapiGenerator/models/DeleteMyWorkRequest.ts
  frontend/src/types/openapiGenerator/models/GetFcstRisk.ts
  frontend/src/types/openapiGenerator/models/GetMyWorksOfTodayResponse.ts
  frontend/src/types/openapiGenerator/models/GetWeatherBriefing.ts
  frontend/src/types/openapiGenerator/models/GetWeatherCondition.ts
  frontend/src/types/openapiGenerator/models/GetWeatherGraph.ts
  frontend/src/types/openapiGenerator/models/LoginRequest.ts
  frontend/src/types/openapiGenerator/models/ModifyMyWorkRequest.ts
  frontend/src/types/openapiGenerator/models/ModifyMyWorkResponse.ts
  frontend/src/types/openapiGenerator/models/MyCropResponse.ts
  frontend/src/types/openapiGenerator/models/RecommendWorksResponse.ts
  frontend/src/types/openapiGenerator/models/RecommendedWorksResponse.ts
  frontend/src/types/openapiGenerator/models/RegisterMyWorkRequest.ts
  frontend/src/types/openapiGenerator/models/RegisterMyWorkResponse.ts
  frontend/src/types/openapiGenerator/models/ValuePerTime.ts
  frontend/src/types/openapiGenerator/models/WeatherRiskDto.ts
  frontend/src/types/openapiGenerator/models/all.ts
  frontend/src/types/openapiGenerator/models/index.ts
Labels: ✨ Feature, 🙌🏻 Setting, 🖼️ FE

#259 [Feat] 로그인 Response에 사용자 nickname 추가
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/controller/AuthController.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/dto/response/LoginResponse.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/service/AuthService.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/common/auth/controller/AuthControllerTest.java
Labels: 🛠️ Fix, 🗃️ BE

#268 [Feat] zustand를 활용한 환경 세팅 및 전역 데이터 관리 #252
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/pages/homePage/components/headline/Headline.tsx
  frontend/src/store/useTimeStore.ts
  frontend/src/store/useUserStore.ts
  frontend/src/store/useWeatherConditionStore.ts
Labels: ✨ Feature, 🙌🏻 Setting, 🖼️ FE

#284 [Feat] 홈페이지 - 날씨 요약 정보 조회 API 연동
  frontend/src/App.tsx
  frontend/src/constants/backgroundTheme.ts
  frontend/src/constants/flatIcons.ts
  frontend/src/constants/glassIcon.ts
  frontend/src/constants/glassMobileIcon.ts
  frontend/src/layouts/Layout.tsx
  frontend/src/pages/homePage/components/headline/Headline.tsx
  frontend/src/types/openapiGenerator/models/GetWeatherGraph.ts
  frontend/src/types/weather.types.ts
Labels: ✨ Feature, 🖼️ FE

#286 [Fix] openapi 기반 타입 생성 스크립트 수정
  frontend/generate_openapi_types.sh
  frontend/src/apis/weather.api.ts
  frontend/src/types/openapiGenerator/index.ts
  frontend/src/types/openapiGenerator/models/CustomResponseBodyGetFcstRiskResponse.ts
  frontend/src/types/openapiGenerator/models/CustomResponseBodyGetSunRiseSetTimeResponse.ts
  frontend/src/types/openapiGenerator/models/CustomResponseBodyGetUVInfoResponse.ts
  frontend/src/types/openapiGenerator/models/CustomResponseBodyGetWeatherBriefingResponse.ts
  frontend/src/types/openapiGenerator/models/CustomResponseBodyGetWeatherConditionResponse.ts
  frontend/src/types/openapiGenerator/models/CustomResponseBodyGetWeatherGraphResponse.ts
  frontend/src/types/openapiGenerator/models/CustomResponseBodyLoginResponse.ts
  frontend/src/types/openapiGenerator/models/GetFcstRiskResponse.ts
  frontend/src/types/openapiGenerator/models/GetSunRiseSetTimeResponse.ts
  frontend/src/types/openapiGenerator/models/GetUVInfoResponse.ts
  frontend/src/types/openapiGenerator/models/GetWeatherBriefingResponse.ts
  frontend/src/types/openapiGenerator/models/GetWeatherConditionResponse.ts
  frontend/src/types/openapiGenerator/models/GetWeatherGraphResponse.ts
  frontend/src/types/openapiGenerator/models/LoginResponse.ts
  frontend/src/types/openapiGenerator/models/all.ts
  frontend/src/types/openapiGenerator/models/index.ts
Labels: 🛠️ Fix, 🖼️ FE

#249 [Feat] 병해충 리스크 엔티티
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/pest/entity/PestCondition.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/pest/entity/PestRisk.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/pest/service/WeatherConditionCode.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/entity/Crop.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/pest/entity/EntityTest.java
Labels: ✨ Feature, 🗃️ BE

#293 [Feat] 날씨 정보 페이지 - 자외선 및 일출몰 API 연동
  frontend/src/apis/weather.api.ts
  frontend/src/pages/weatherBoardPage/WeatherBoardPage.tsx
  frontend/src/pages/weatherBoardPage/components/weatherBoardSunset/WeatherBoardSunset.tsx
  frontend/src/pages/weatherBoardPage/components/weatherBoardUV/WeatherBoardUV.tsx
Labels: ✨ Feature, 🖼️ FE

#264 [Feat] 요청 값이 null인 경우에 code 세분화
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/controller/AuthController.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/dto/request/LoginRequest.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/member/exception/MemberResponseStatus.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/controller/MyWorkController.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/dto/request/DeleteMyWorkRequest.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/dto/request/ModifyMyWorkRequest.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/dto/request/RegisterMyWorkRequest.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/exception/WorkResponseStatus.java
Labels: ✨ Feature, 🗃️ BE

#272 [Fix] 완료되지 않은 농작업도 삭제할 수 있도록 변경
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/service/MyWorkService.java
Labels: 🛠️ Fix, 🗃️ BE

#277 [Feat] 기상 그래프 & 리스크 조회 API 수정
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/enums/WeatherCondition.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/entity/ShortTermWeatherForecast.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/entity/WeatherRisk.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/Briefing.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/LinePoint.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/WeatherService.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/util/WeatherRiskIntervalMerger.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/weather/WeatherBriefingTest.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/weather/WeatherServiceTest.java
Labels: 🛠️ Fix, ✨ Feature, 🗃️ BE

#269 [Feat] 7일 기상 예보 조회 기능
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/member/entity/Farm.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/controller/WeatherController.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/dto/response/GetSevenDaysForecastResponse.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/entity/SevenDayWeatherForecast.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/entity/SevenDayWeatherForecastId.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/exception/WeatherResponseStatus.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/repository/SevenDayWeatherForecastRepository.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/WeatherService.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/member/MemberServiceTest.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/weather/WeatherBriefingTest.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/weather/WeatherServiceTest.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/weather/entity/SevenDayWeatherForecastTest.java
Labels: ✨ Feature, 🗃️ BE

#297 [Feat] 일일 최고 습도 조회 API 구현
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/controller/WeatherController.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/dto/response/GetHumidityResponse.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/exception/WeatherResponseStatus.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/repository/DashboardTodayWeatherRepository.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/WeatherService.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/projection_entity/HumidityInfo.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/weather/WeatherServiceTest.java
Labels: ✨ Feature, 🗃️ BE

#303 [Feat] 일일 최고 강수량 조회 API 구현
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/controller/WeatherController.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/dto/response/GetDailyMaxPrecipitationResponse.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/exception/WeatherResponseStatus.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/repository/DashboardTodayWeatherRepository.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/WeatherService.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/projection_entity/PrecipitationInfo.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/weather/WeatherServiceTest.java
Labels: ✨ Feature, 🗃️ BE

#316 [Fix] Precipitation 오타 수정
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/enums/WeatherMetric.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/controller/WeatherController.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/dto/response/GetTemperatureResponse.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/WeatherService.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/DailyTemperatureJobConfig.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/JobScheduler.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/common/entity/DashboardWeatherForecast.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/common/entity/DashboardWeatherForecastId.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/common/entity/SevenDayWeatherForecast.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/common/entity/SevenDayWeatherForecastId.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/common/enums/WeatherCondition.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/common/params/JobParams.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/common/repository/DashboardWeatherForecastRepository.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/dailyTemperature/processor/DailyTemperatureProcessor.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/dailyTemperature/processor/dto/DailyTemperatureProcessorResponseDto.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/dailyTemperature/reader/DailyTemperatureReader.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/dailyTemperature/reader/dto/DailyTemperatureReaderResponseDto.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/dailyTemperature/writer/DailyTemperatureWriter.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/seven_days_weather_forecast/dto/SevenDayWeatherConditionDto.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/seven_days_weather_forecast/processor/SevenDayWeatherConditionProcessor.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/seven_days_weather_forecast/writer/SevenDayTemperatureWriter.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/shortTermWeatherForecast/processor/WeatherProcessor.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/writer/repository/SevenDayWeatherForecastRepository.java
Labels: 🛠️ Fix, 🗃️ BE

#319 [Feat] 홈페이지 - 메인그래프 API 연동 및 그래프 UI 이슈 해결
  frontend/src/apis/weather.api.ts
  frontend/src/constants/flatIcons.ts
  frontend/src/constants/graphMenu.ts
  frontend/src/pages/homePage/components/customizedDot/CustomizedDot.tsx
  frontend/src/pages/homePage/components/customizedTootip/CustomizedTooltip.tsx
  frontend/src/pages/homePage/components/graphMenu/GraphMenu.style.ts
  frontend/src/pages/homePage/components/mainGraph/MainGraph.tsx
  frontend/src/pages/homePage/components/mainLineChart/MainLineChart.style.ts
  frontend/src/pages/homePage/components/mainLineChart/MainLineChart.tsx
  frontend/src/pages/homePage/components/weatherRiskText/WeatherRiskText.tsx
  frontend/src/pages/homePage/components/workContainer/WorkContainer.tsx
  frontend/src/pages/homePage/mobile/MobileHomePage.tsx
  frontend/src/pages/homePage/utils/lineChartUtil.ts
  frontend/src/types/weather.types.ts
  frontend/src/utils/getUnit.ts
Labels: 🛠️ Fix, ✨ Feature, 🖼️ FE

#308 [Feat] 내 농작업 이력 (weekly) 조회 기능
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/controller/MyWorkController.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/dto/response/GetMyWorksOfWeeklyResponse.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/entity/MyWork.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/exception/WorkResponseStatus.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/repository/MyWorkRepository.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/service/MyWorkService.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/work/entity/MyWorkTest.java
Labels: ✨ Feature, 🗃️ BE

#336 [Feat] 최고 풍속 화살표 아이콘 회전 애니메이션 구현
  frontend/src/pages/weatherBoardPage/components/weatherBoardWind/WeatherBoardWind.style.ts
  frontend/src/pages/weatherBoardPage/components/weatherBoardWind/WeatherBoardWind.tsx
Labels: ✨ Feature, 🖼️ FE

#343 [Feat] 홈페이지 - 기상 브리핑 및 리스크 조회 API 연동
  frontend/src/apis/weather.api.ts
  frontend/src/pages/homePage/components/customizedDot/CustomizedDot.tsx
  frontend/src/pages/homePage/components/headline/Headline.tsx
  frontend/src/pages/homePage/components/mainGraph/MainGraph.tsx
  frontend/src/pages/homePage/components/mainLineChart/MainLineChart.tsx
  frontend/src/pages/homePage/components/weatherRiskText/WeatherRiskText.tsx
  frontend/src/pages/homePage/components/workContainer/WorkContainer.tsx
  frontend/src/pages/homePage/desktop/DesktopHomePage.tsx
  frontend/src/pages/homePage/utils/lineChartUtil.ts
  frontend/src/utils/formatTimeUtil.ts
  frontend/src/utils/getUnit.ts
Labels: ✨ Feature, 🖼️ FE

#346 [Feat] 내 농작업 추가, 삭제 api 연동
  frontend/src/apis/myWork.api.ts
  frontend/src/constants/workScheduleData.ts
  frontend/src/constants/workTimePx.ts
  frontend/src/pages/homePage/components/workActiveToolTip/WorkActiveToolTip.style.ts
  frontend/src/pages/homePage/components/workActiveToolTip/WorkActiveToolTip.tsx
  frontend/src/pages/homePage/components/workCell/WorkCell.tsx
  frontend/src/pages/homePage/contexts/WorksProvider.tsx
  frontend/src/pages/homePage/hooks/useCreateWorkBlock.ts
  frontend/src/pages/homePage/utils/updateBlockWorkTime.ts
  frontend/src/types/openapiGenerator/models/GetWeatherGraphResponse.ts
  frontend/src/types/openapiGenerator/models/RecommendationDurations.ts
  frontend/src/types/openapiGenerator/models/RecommendedWorksResponse.ts
  frontend/src/types/openapiGenerator/models/all.ts
Labels: ✨ Feature, 🖼️ FE

#329 [Feat] 시간별 기온 조회 API 구현
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/controller/WeatherController.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/dto/response/GetTemperatureResponse.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/entity/DashboardWeatherForecast.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/entity/DashboardWeatherForecastId.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/exception/WeatherResponseStatus.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/repository/DashboardWeatherForecastRepository.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/WeatherService.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/weather/WeatherServiceTest.java
Labels: ✨ Feature, 🗃️ BE

#351 [Feat] 홈페이지 - 메인 그래프 Tooltip 관련 이슈 해결
  frontend/src/pages/homePage/components/customizedTootip/CustomizedTooltip.tsx
  frontend/src/pages/homePage/components/mainLineChart/MainLineChart.style.ts
  frontend/src/pages/homePage/components/mainLineChart/MainLineChart.tsx
  frontend/src/pages/homePage/components/portalTooltipWrapper/PortalTooltipWrapper.tsx
Labels: 🛠️ Fix, 🖼️ FE

#408 [Feat] accessToken reissue 기능
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/controller/AuthController.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/service/AuthService.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/member/repository/MemberRepository.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/common/auth/service/AuthServiceTest.java
Labels: ✨ Feature, 🗃️ BE

#414 [Feat] 메인 그래프 조회 API 호출 최적화
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/App.tsx
  frontend/src/main.tsx
  frontend/src/pages/homePage/components/workContainer/WorkContainer.tsx
  frontend/src/pages/homePage/hooks/useWeatherGraphQuery.ts
  frontend/src/pages/weatherBoardPage/components/weatherBoardTemperature/WeatherBoardTemperature.tsx
Labels: ✨ Feature, 🖼️ FE

#412 [Feat] 기상 리스크별 피해 목록 조회 api 연동
  frontend/src/apis/damage.api.ts
  frontend/src/pages/homePage/components/damageCard/DamageCard.style.ts
  frontend/src/pages/homePage/components/damageInfoCard/DamageInfoCard.tsx
  frontend/src/pages/homePage/components/damagePests/DamagePests.tsx
  frontend/src/styles/GlobalStyles.tsx
  frontend/src/types/openapiGenerator/models/all.ts
Labels: ✨ Feature, 🖼️ FE

#417 [Feat] 병충해 api 연동
  frontend/src/apis/damage.api.ts
  frontend/src/pages/homePage/components/damageInfoCard/DamageInfoCard.tsx
  frontend/src/pages/homePage/components/damagePests/DamagePests.tsx
  frontend/src/pages/homePage/hooks/useDamagePests.ts
  frontend/src/pages/homePage/hooks/useDamagePestsUI.ts
Labels: ✨ Feature, 🖼️ FE

#419 [Fix] accessToken 재발급 시 refreshToken을 쿠키로 보내도록 변경
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/controller/AuthController.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/dto/response/LoginResponse.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/service/AuthService.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/response/ResponseUtil.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/common/auth/controller/AuthControllerTest.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/common/auth/service/AuthServiceTest.java
Labels: 🛠️ Fix, 🗃️ BE

#422 [Fix] refreshToken cookie에 httpOnly 설정
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/response/ResponseUtil.java
Labels: 🛠️ Fix, 🗃️ BE

#424 [Fix] refreshToken cookie에 sameSite none 설정
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/response/ResponseUtil.java
Labels: 🛠️ Fix, 🗃️ BE

#413 [Fix] 요청의 MyCropId가 요청자의 소유가 아닌 경우 예외 처리
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/damage/pest/package-info.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/damage/pest/service/PestService.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/exception/CropResponseStatus.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/pest/service/PestServiceTest.java
Labels: 🛠️ Fix, 🗃️ BE

#429 [Fix] cookie secure true 설정
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/response/ResponseUtil.java
Labels: 🛠️ Fix, 🗃️ BE

#431 fix: cookie 생성 시 sameSite를 "Lax"로 설정
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/response/ResponseUtil.java
Labels: 🛠️ Fix, 🗃️ BE

#437 [Fix] cookie secure true 설정
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/response/ResponseUtil.java
Labels: 🛠️ Fix, 🗃️ BE

#439 [Fix] accessToken 재발급 시 refreshToken도 저장
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/service/AuthService.java
Labels: 🛠️ Fix, 🗃️ BE

#444 [Fix] accessToken 재발급 시 refreshToken 오류 해결
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/service/AuthService.java
Labels: 🛠️ Fix, 🗃️ BE

#445 fix: PestServiceTest 오류 해결
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/pest/service/PestServiceTest.java
Labels: 🛠️ Fix, 🗃️ BE

#450 [Fix] 농작업 추천 시간대 최대값을 4시간으로 제한
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/util/WorkScheduleCalculator.java
Labels: 🛠️ Fix, 🗃️ BE

#451 [Feat] 접속 기기가 모바일인지 판단하고 그에 따른 제한 처리
  frontend/src/App.tsx
  frontend/src/apis/http.ts
  frontend/src/components/common/ProtectedRoute.tsx
  frontend/src/layouts/Layout.tsx
  frontend/src/pages/accessDeniedPage/AccessDeniedPage.style.tsx
  frontend/src/pages/accessDeniedPage/AccessDeniedPage.tsx
  frontend/src/pages/homePage/HomePage.tsx
  frontend/src/pages/homePage/components/mobileTodo/MobileTodo.style.ts
  frontend/src/pages/homePage/components/mobileTodo/MobileTodo.tsx
  frontend/src/pages/notFoundPage/NotFoundPage.style.tsx
  frontend/src/pages/notFoundPage/NotFoundPage.tsx
  frontend/src/routes/Router.tsx
  frontend/src/store/useIsMobileStore.ts
Labels: ✨ Feature, 🖼️ FE

#454 [Feat] 농작업 완료 시 작업 인원 집계 구현
  backend/build.gradle
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/NyeoreumnagiApplication.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/util/GeoUtil.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/member/repository/FarmRepository.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/entity/WorkActivityFact.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/event/MyWorkCompletedEvent.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/event/MyWorkCompletedEventListener.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/repository/WorkActivityFactRepository.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/service/MyWorkService.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/service/NearbyAggregationService.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/service/RecommendedWorkService.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/work/entity/WorkActivityFactTest.java
Labels: 🛠️ Fix, 🗃️ BE

#465 [Fix] findByIdAndMember_Id() -> findById() 후 memberId 동일성 검증
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/service/MyWorkService.java
Labels: 🛠️ Fix, 🗃️ BE

#456 [Refactor] dnd 로직 변경 및 리팩토링
  .github/workflows/frontend-ci.yml
  frontend/src/components/dnd/DragOverlay.style.ts
  frontend/src/components/dnd/DragOverlay.tsx
  frontend/src/components/dnd/dragContainer/DragContainer.tsx
  frontend/src/components/dnd/draggableItem/DraggableItem.tsx
  frontend/src/components/dnd/draggingItem/DraggingItem.tsx
  frontend/src/components/dnd/hooks/useBlocksTransition.ts
  frontend/src/components/dnd/hooks/useDragBlock.ts
  frontend/src/components/dnd/hooks/useResizeBlock.ts
  frontend/src/components/dnd/hooks/useResizeCollision.ts
  frontend/src/components/dnd/utils/animateBlock.ts
  frontend/src/components/dnd/utils/collisionUtils.ts
  frontend/src/components/dnd/utils/isFullyOverlapped.ts
  frontend/src/components/dnd/utils/isTimeOverlapping.ts
  frontend/src/components/dnd/utils/resolveCollision.ts
  frontend/src/constants/workTimeCoordinate.ts
  frontend/src/hooks/dnd/useDragAndDrop.ts
  frontend/src/hooks/dnd/useRevertPosition.ts
  frontend/src/hooks/useSetPointerEvents.ts
  frontend/src/pages/homePage/components/btnCreateWork/BtnCreateWork.tsx
  frontend/src/pages/homePage/components/mainGraph/MainGraph.tsx
  frontend/src/pages/homePage/components/registerWorkContainer/RegisterWorkContainer.tsx
  frontend/src/pages/homePage/components/workActiveToolTip/WorkActiveToolTip.tsx
  frontend/src/pages/homePage/components/workCardRegister/WorkCardRegister.style.ts
  frontend/src/pages/homePage/components/workCardRegister/WorkCardRegister.tsx
  frontend/src/pages/homePage/components/workCell/WorkCell.tsx
  frontend/src/pages/homePage/components/workCellsContainer/WorkCellsContainer.tsx
  frontend/src/pages/homePage/components/workContainer/WorkContainer.tsx
  frontend/src/pages/homePage/contexts/ContainerContext.tsx
  frontend/src/pages/homePage/contexts/WorkBlocksContext.tsx
  frontend/src/pages/homePage/contexts/useContainer.ts
  frontend/src/pages/homePage/contexts/useWorkBlocks.ts
  frontend/src/pages/homePage/desktop/DesktopHomePage.tsx
  frontend/src/pages/homePage/hooks/useContainer.ts
  frontend/src/pages/homePage/hooks/useDragWorkBlock.ts
  frontend/src/pages/homePage/hooks/work/useChangeTimeByResize.ts
  frontend/src/pages/homePage/hooks/work/useCreateWorkBlock.ts
  frontend/src/pages/homePage/hooks/work/useRecommendedWorks.ts
  frontend/src/pages/homePage/hooks/work/useWorkBlocks.ts
  frontend/src/pages/homePage/utils/work/calculateTimeToPosition.ts
  frontend/src/pages/homePage/utils/work/getInitialWorkBlocks.ts
  frontend/src/pages/homePage/utils/work/sortWorkBlocks.ts
  frontend/src/pages/homePage/utils/work/updateBlockTime.ts
  frontend/src/pages/homePage/utils/work/updateBlockTimeOnServer.ts
  frontend/src/pages/homePage/utils/work/updateBlockWorkTime.ts
  frontend/src/pages/homePage/utils/work/updateWorkTimeByPos.ts
  frontend/src/pages/homePage/utils/work/workContainerUtils.ts
  frontend/src/types/blockType.type.ts
  frontend/src/types/position.type.ts
  frontend/src/types/size.type.ts
  frontend/src/types/workCard.type.ts
  frontend/src/utils/isInBound.ts
Labels: ✨ Feature, 🔨 Refactor, 🖼️ FE

#467 [Fix] 날씨 정보 페이지 - API 호출 이전에 초기 상태 화면 렌더링 막기
  frontend/src/components/common/CircularSpinner.tsx
  frontend/src/layouts/Layout.tsx
  frontend/src/pages/homePage/components/headline/Headline.tsx
  frontend/src/pages/homePage/components/mobileHeader/MobileHeader.tsx
  frontend/src/pages/weatherBoardPage/WeatherBoardPage.style.ts
  frontend/src/pages/weatherBoardPage/WeatherBoardPage.tsx
  frontend/src/pages/weatherBoardPage/components/weatherBoardDust/WeatherBoardDust.tsx
  frontend/src/pages/weatherBoardPage/components/weatherBoardHumidity/WeatherBoardHumidity.tsx
  frontend/src/pages/weatherBoardPage/components/weatherBoardPrecipitation/WeatherBoardPrecipitation.tsx
  frontend/src/pages/weatherBoardPage/components/weatherBoardSunset/WeatherBoardSunset.tsx
  frontend/src/pages/weatherBoardPage/components/weatherBoardTemperature/WeatherBoardTemperature.tsx
  frontend/src/pages/weatherBoardPage/components/weatherBoardUV/WeatherBoardUV.tsx
  frontend/src/pages/weatherBoardPage/components/weatherBoardWeekly/WeatherBoardWeekly.tsx
  frontend/src/pages/weatherBoardPage/components/weatherBoardWind/WeatherBoardWind.tsx
Labels: 🛠️ Fix, 🔨 Refactor, 🖼️ FE

#471 [Feat] 작업 일정 width가 작을 경우 hover 시 Tooltip 기능 구현
  frontend/src/pages/homePage/components/workCardRegister/WorkCardRegister.style.ts
  frontend/src/pages/homePage/components/workCardRegister/WorkCardRegister.tsx
  frontend/src/pages/homePage/components/workCardRegisterContent/WorkCardRegisterContent.style.ts
  frontend/src/pages/homePage/components/workCardRegisterContent/WorkCardRegisterContent.tsx
Labels: ✨ Feature, 🖼️ FE

#474 [Refactor] Batch writer에서 MySQL Bulk update 적용
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/BatchConfiguration.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/JobScheduler.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/dailyTemperature/processor/DailyTemperatureProcessor.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/daily_high/writer/DailyHighWriter.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/sunRiseSet/writer/SunRiseSetWriter.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/ultraviolet/reader/UVApiCaller.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/ultraviolet/writer/UVWriter.java
Labels: 🛠️ Fix, 🗃️ BE

#478 [Feat] 현재보다 이전 시간인 작업 일정 표시
  frontend/src/components/common/PortalToolTip.tsx
  frontend/src/components/toolTip/ToolTip.tsx
  frontend/src/pages/homePage/components/workCardRegister/WorkCardRegister.style.ts
  frontend/src/pages/homePage/components/workCardRegister/WorkCardRegister.tsx
  frontend/src/pages/homePage/components/workCardRegisterContent/WorkCardRegisterContent.style.ts
  frontend/src/pages/homePage/components/workCardRegisterContent/WorkCardRegisterContent.tsx
  frontend/src/pages/homePage/utils/work/getInitialWorkBlocks.ts
Labels: ✨ Feature, 🖼️ FE

#482 [Hotfix] Batch 프로젝트와 api server 프로젝트 간 entity 불일치로 인한 오류 해결
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/entity/WeatherRisk.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/weather/WeatherBriefingTest.java
Labels: 🛠️ Fix, 🗃️ BE

#487 [Fix] 농작업 추천 목록 개수를 최대 5개로 제한
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/service/RecommendedWorkService.java
Labels: 🛠️ Fix, 🗃️ BE

#489 [Feat] 드래그 시 작업 등록
  frontend/src/components/dnd/dragContainer/DragContainer.tsx
  frontend/src/components/dnd/utils/collisionUtils.ts
  frontend/src/pages/homePage/components/btnCreateWork/BtnCreateWork.tsx
  frontend/src/pages/homePage/components/workCardRegister/WorkCardRegister.tsx
  frontend/src/pages/homePage/components/workCell/WorkCell.tsx
  frontend/src/pages/homePage/components/workContainer/WorkContainer.tsx
  frontend/src/pages/homePage/hooks/work/useCreateWorkBlock.ts
Labels: ✨ Feature, 🖼️ FE

#491 [Hotifx] 기상 그래프 24시간 이내만 반환하도록 수정
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/WeatherService.java
Labels: 🛠️ Fix, 🗃️ BE

#488 [Fix] Batch Job 실패했을 때 shadow table이 rename되지 않도록 수정
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/shortTermWeatherForecast/reader/WeatherReader.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/shortTermWeatherForecast/writer/WeatherWriter.java
Labels: 🛠️ Fix, 🗃️ BE

#497 [Feat] 네브바 로고 라우팅 추가, 스크롤 아래로 내릴 시 네브바 안보이게 구현
  frontend/src/layouts/navBar/NavBar.styles.ts
  frontend/src/layouts/navBar/NavBar.tsx
Labels: ✨ Feature, 🖼️ FE

#501 [Release] BE 1.0.4 - 8월 22일 데모데이를 위한 dev merge
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/entity/ShortTermWeatherForecast.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/entity/ShortTermWeatherForecastId.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/entity/WeatherRisk.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/repository/ShortTermWeatherForecastRepository.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/WeatherService.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/util/WeatherRiskIntervalMerger.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/service/RecommendedWorkService.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/util/WorkScheduleCalculator.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/weather/WeatherBriefingTest.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/weather/WeatherServiceTest.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/weather/entity/ShortTermWeatherForecastTest.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/common/entity/ShortTermWeatherForecast.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/common/entity/ShortTermWeatherForecastId.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/common/entity/ShortTermWeatherForecastShadow.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/dailyTemperature/processor/DailyTemperatureProcessor.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/shortTermWeatherForecast/processor/WeatherProcessor.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/shortTermWeatherForecast/processor/utils/ForecastTimeUtils.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/shortTermWeatherForecast/reader/WeatherReader.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/shortTermWeatherForecast/writer/WeatherWriter.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/shortTermWeatherForecast/writer/dto/ShortTermWeatherDto.java
  batch/src/test/java/com/ImSnacks/NyeoreumnagiBatch/ForecastTimeUtilsTest.java
Labels: 🗃️ BE, Release

#498 [Fix] 생육단계 Id로 추천 농작업 목록 조회 시 fetch join 사용
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/lifecycle/repository/LifeCycleAndRecommendedWorkRepository.java
Labels: 🛠️ Fix, 🗃️ BE

#524 [Fix] 농작업 추천 시 단기 예보 정렬 오류 해결
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/util/WorkScheduleCalculator.java
Labels: 🛠️ Fix, 🗃️ BE

#526 [Feat] 작업 추가/삭제 시 재정렬 및 애니메이팅 추가
  frontend/src/pages/homePage/components/registerWorkContainer/RegisterWorkContainer.style.ts
  frontend/src/pages/homePage/components/registerWorkContainer/RegisterWorkContainer.tsx
  frontend/src/pages/homePage/components/workCell/WorkCell.style.ts
  frontend/src/pages/homePage/components/workCell/WorkCell.tsx
  frontend/src/pages/homePage/components/workCellsContainer/WorkCellsContainer.style.ts
  frontend/src/pages/homePage/hooks/work/useCreateWorkBlock.ts
  frontend/src/pages/homePage/hooks/work/useWorkBlocks.ts
  frontend/src/pages/myFarmPage/components/myCropInfo/MyCropInfo.tsx
  frontend/src/pages/myFarmPage/components/myFarmHeader/MyFarmHeader.style.ts
Labels: ✨ Feature, 🖼️ FE

#527 [Fix] 7일 예보 Job 실패 오류 개선
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/WeatherService.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/WeatherJobConfig.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/common/enums/WeatherCondition.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/seven_days_weather_forecast/dto/SevenDayTemperatureForecastDto.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/seven_days_weather_forecast/dto/SevenDayTotalForecastResponseDto.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/seven_days_weather_forecast/processor/SevenDayTemperatureProcessor.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/seven_days_weather_forecast/reader/SevenDaysApiCaller.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/seven_days_weather_forecast/writer/SevenDayTemperatureWriter.java
Labels: 🛠️ Fix, 🗃️ BE

#530 [Feat] 농작업 상태를 다시 `INCOMPLETED`로 변경하면 집계에서 제외되도록 구현
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/entity/WorkActivityFact.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/event/MyWorkCompletedEvent.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/event/MyWorkCompletedEventListener.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/repository/WorkActivityFactRepository.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/service/MyWorkService.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/service/NearbyAggregationService.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/service/RecommendedWorkService.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/work/entity/WorkActivityFactTest.java
Labels: 🛠️ Fix, 🗃️ BE

#531 [Feat] 1차 QA 피드백 반영
  frontend/src/pages/homePage/components/btnCreateWork/BtnCreateWork.style.ts
  frontend/src/pages/homePage/components/damageInfoCard/DamageInfoCard.style.ts
  frontend/src/pages/homePage/components/damageInfoCard/DamageInfoCard.tsx
  frontend/src/pages/homePage/components/workContainer/WorkContainer.style.ts
  frontend/src/pages/homePage/components/workContainer/WorkContainer.tsx
  frontend/src/pages/myFarmPage/MyFarmPage.style.ts
  frontend/src/pages/myFarmPage/components/weekNavigator/WeekNavigator.style.ts
  frontend/src/pages/myFarmPage/components/weekNavigator/WeekNavigator.tsx
  frontend/src/pages/myFarmPage/components/weeklyCalendar/WeeklyCalendar.style.ts
  frontend/src/pages/myFarmPage/components/weeklyCalendar/WeeklyCalendar.tsx
  frontend/src/pages/myFarmPage/components/workSchedule/WorkSchedule.tsx
Labels: ✨ Feature, 🖼️ FE

#532 [Fix] 기상 브리핑 메시지의 기상 특보 시작 시간 요건 변경
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/Briefing.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/WeatherService.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/weather/WeatherBriefingTest.java
Labels: 🛠️ Fix, 🗃️ BE

#536 [Feat] 작업 일정 컨테이너 height 동적 증가 및 정각에 refetch 기능 구현
  frontend/src/components/dnd/utils/isFullyOverlapped.ts
  frontend/src/components/dnd/utils/resolveCollision.ts
  frontend/src/constants/workTimeCoordinate.ts
  frontend/src/pages/homePage/components/workCell/WorkCell.style.ts
  frontend/src/pages/homePage/components/workCellsContainer/WorkCellsContainer.style.ts
  frontend/src/pages/homePage/components/workCellsContainer/WorkCellsContainer.tsx
  frontend/src/pages/homePage/components/workContainer/WorkContainer.tsx
  frontend/src/pages/homePage/hooks/work/useCreateWorkBlock.ts
  frontend/src/pages/homePage/hooks/work/useWorkBlocks.ts
  frontend/src/pages/homePage/utils/work/sortWorkBlocks.ts
  frontend/src/store/useMaxLayerStore.ts
Labels: ✨ Feature, 🖼️ FE

#538 [Hotfix] 기상 그래프 조회 API에서 24시간 이후 데이터까지만 조회안되는 오류 해결
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/WeatherService.java
Labels: 🛠️ Fix, 🗃️ BE

#540 [Fix] 추천 농작업에서 강수 기준 mm 를 상향 조정
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/util/WorkScheduleCalculator.java
Labels: 🛠️ Fix, 🗃️ BE

#544 [Feat] 배치 weatherJob에 비동기 processor와 비동기 writer 적용
  batch/build.gradle
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/AsyncWeatherJobConfig.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/JobScheduler.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/WeatherJobConfig.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/shortTermWeatherForecast/processor/ImprovedApiCaller.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/shortTermWeatherForecast/processor/ImprovedWeatherProcessor.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/shortTermWeatherForecast/reader/ApiCaller.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/shortTermWeatherForecast/reader/UniqueNxNyReader.java
  batch/src/main/resources/application.yml
Labels: ✨ Feature, 🗃️ BE

#545 [Fix] 1차 QA 버그 수정
  frontend/src/components/common/CircularSpinner.tsx
  frontend/src/pages/accessDeniedPage/AccessDeniedPage.style.ts
  frontend/src/pages/accessDeniedPage/AccessDeniedPage.tsx
  frontend/src/pages/homePage/components/mainGraph/MainGraph.tsx
  frontend/src/pages/homePage/components/mobileHeader/MobileHeader.tsx
  frontend/src/pages/homePage/components/mobileWorkCard/MobileWorkCard.tsx
  frontend/src/pages/homePage/mobile/MobileHomePage.tsx
  frontend/src/pages/loginPage/LoginPage.style.ts
  frontend/src/pages/loginPage/LoginPage.tsx
  frontend/src/pages/notFoundPage/NotFoundPage.style.ts
  frontend/src/pages/weatherBoardPage/WeatherBoardPage.tsx
  frontend/src/pages/weatherBoardPage/components/temperatureDot/TemperatureDot.tsx
  frontend/src/pages/weatherBoardPage/components/weatherBoardDust/WeatherBoardDust.style.ts
  frontend/src/pages/weatherBoardPage/components/weatherBoardDust/WeatherBoardDust.tsx
  frontend/src/pages/weatherBoardPage/components/weatherBoardHumidity/WeatherBoardHumidity.style.ts
  frontend/src/pages/weatherBoardPage/components/weatherBoardHumidity/WeatherBoardHumidity.tsx
  frontend/src/pages/weatherBoardPage/components/weatherBoardPrecipitation/WeatherBoardPrecipitation.style.ts
  frontend/src/pages/weatherBoardPage/components/weatherBoardPrecipitation/WeatherBoardPrecipitation.tsx
  frontend/src/pages/weatherBoardPage/components/weatherBoardSunset/WeatherBoardSunset.style.ts
  frontend/src/pages/weatherBoardPage/components/weatherBoardSunset/WeatherBoardSunset.tsx
  frontend/src/pages/weatherBoardPage/components/weatherBoardTemperature/WeatherBoardTemperature.tsx
  frontend/src/pages/weatherBoardPage/components/weatherBoardUV/WeatherBoardUV.tsx
  frontend/src/pages/weatherBoardPage/components/weatherBoardWeekly/WeatherBoardWeekly.tsx
  frontend/src/pages/weatherBoardPage/components/weatherBoardWind/WeatherBoardWind.tsx
Labels: 🛠️ Fix, 🖼️ FE

#548 [Fix] 리액트 쿼리 적용 후 post/delete/patch 시 데이터 업데이트 안됨 문제 해결
  frontend/src/components/dnd/draggableItem/DraggableItem.tsx
  frontend/src/components/dnd/hooks/useDragBlock.ts
  frontend/src/components/dnd/hooks/useResizeBlock.ts
  frontend/src/pages/homePage/hooks/work/useWorkBlocks.ts
  frontend/src/pages/homePage/utils/work/sortWorkBlocks.ts
  frontend/src/pages/homePage/utils/work/updateBlockTimeOnServer.ts
Labels: ✨ Feature, 🖼️ FE

#549 [Fix] UI 디테일 (툴팁 위치, hover 효과) 수정, 작업일정 과거로 수정 비활성화
  frontend/src/components/common/PortalToolTip.tsx
  frontend/src/components/dnd/hooks/useDragBlock.ts
  frontend/src/pages/homePage/components/btnCreateWork/BtnCreateWork.style.ts
  frontend/src/pages/homePage/components/btnCreateWork/BtnCreateWork.tsx
  frontend/src/pages/homePage/components/workActiveToolTip/WorkActiveToolTip.style.ts
  frontend/src/pages/homePage/components/workActiveToolTip/WorkActiveToolTip.tsx
  frontend/src/pages/homePage/components/workCardRegisterContent/WorkCardRegisterContent.tsx
  frontend/src/pages/homePage/components/workCellsContainer/WorkCellsContainer.tsx
Labels: ✨ Feature, 🖼️ FE

#552 [Refactor] 기상청 단기예보 batch 실패시 tomorrow.io 호출하도록 수정
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/shortTermWeatherForecast/processor/AlterApiCaller.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/shortTermWeatherForecast/processor/ImprovedApiCaller.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/shortTermWeatherForecast/processor/ImprovedWeatherProcessor.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/shortTermWeatherForecast/reader/WeatherReader.java
  batch/src/main/resources/application.yml
Labels: 🔨 Refactor, 🗃️ BE

#558 [Release] BE 1.0.6 - code freeze 이전 최최종 Release
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/shortTermWeatherForecast/reader/dto/VilageFcstResponseDto.java
Labels: 🛠️ Fix, 🗃️ BE, Release

#561 [Docs] README 작성 (인프라 구조도 수정)
  README.md
Labels: 📃 Docs

#560 [Refactor] 미사용 유틸 삭제 및 리팩토링/ 스크롤 이벤트 스로틀 적용
  frontend/src/constants/workTimeCoordinate.ts
  frontend/src/constants/workTimePx.ts
  frontend/src/hooks/useThrottle.ts
  frontend/src/layouts/navBar/NavBar.tsx
  frontend/src/lib/dnd/hooks/useDragBlock.ts
  frontend/src/lib/dnd/hooks/useResizeBlock.ts
  frontend/src/lib/dnd/hooks/useResizeCollision.ts
  frontend/src/lib/dnd/utils/animateBlock.ts
  frontend/src/lib/dnd/utils/collisionUtils.ts
  frontend/src/lib/dnd/utils/isFullyOverlappedUtil.ts
  frontend/src/lib/dnd/utils/isInBoundUtil.ts
  frontend/src/lib/dnd/utils/isTimeOverlappingUtil.ts
  frontend/src/lib/dnd/utils/resolveCollision.ts
  frontend/src/lib/dnd/utils/snapToGridUtil.ts
  frontend/src/pages/homePage/desktop/components/workActiveToolTip/WorkActiveToolTip.tsx
  frontend/src/pages/homePage/desktop/components/workCellsContainer/WorkCellsContainer.style.ts
  frontend/src/pages/homePage/desktop/components/workContainer/WorkContainer.tsx
  frontend/src/pages/homePage/desktop/hooks/useChangeTimeByResize.ts
  frontend/src/pages/homePage/desktop/hooks/useCreateWorkBlock.ts
  frontend/src/pages/homePage/desktop/hooks/useWorkBlocks.ts
  frontend/src/pages/homePage/desktop/utils/calculateTimeToPositionUtil.ts
  frontend/src/pages/homePage/desktop/utils/getInitialWorkBlocksUtil.ts
  frontend/src/pages/homePage/desktop/utils/sortWorkBlocksUtil.ts
  frontend/src/pages/homePage/desktop/utils/updateBlockTimeOnServer.ts
  frontend/src/pages/homePage/desktop/utils/updateBlockTimeUtil.ts
  frontend/src/pages/homePage/desktop/utils/updateBlockWorkTime.ts
  frontend/src/pages/homePage/desktop/utils/updateWorkTimeByPosUtil.ts
  frontend/src/pages/homePage/desktop/utils/workContainerUtils.ts
Labels: ✨ Feature, 🔨 Refactor, 🖼️ FE

#564 docs: README 작성 (api -> API)
  README.md
Labels: 📃 Docs

#567 fix: 브리핑에서 시작시각과 종료시각이 같은 기상 리스크는 무시하도록 처리
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/WeatherService.java
Labels: 🛠️ Fix

#568 [Feat] 테스트 로그인 버튼 추가
  frontend/src/pages/homePage/desktop/components/workContainer/WorkContainer.tsx
  frontend/src/pages/loginPage/LoginPage.style.ts
  frontend/src/pages/loginPage/LoginPage.tsx
  frontend/src/pages/loginPage/hooks/useLogin.ts
  frontend/src/pages/weatherBoardPage/hooks/useWeatherQuery.ts
Labels: ✨ Feature, 🖼️ FE

#573 [Docs] readme 데모 영상 수정 및 FE 디렉토리 구조 추가
  README.md
Labels: 📃 Docs

#575 [Hotfix] 단기예보 batch 1시간 이전 정보 저장하도록 수정
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/shortTermWeatherForecast/writer/WeatherWriter.java
Labels: 🛠️ Fix, 🗃️ BE

#574 [Release] FE 1.0.7
  frontend/src/pages/homePage/desktop/components/workContainer/WorkContainer.tsx
  frontend/src/pages/loginPage/LoginPage.style.ts
  frontend/src/pages/loginPage/LoginPage.tsx
  frontend/src/pages/loginPage/hooks/useLogin.ts
  frontend/src/pages/weatherBoardPage/hooks/useWeatherQuery.ts
Labels: 🖼️ FE, Release

#578 [Fix] .github/workflows/frontend-cd 2.yml 삭제
  .github/workflows/frontend-cd 2.yml
  README.md
Labels: 🛠️ Fix

#577 [Release] 1.0.7 최종 배포입니다.
  .github/workflows/frontend-cd 2.yml
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/entity/WeatherRisk.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/Briefing.java
  backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/WeatherService.java
  backend/src/test/java/com/imsnacks/Nyeoreumnagi/weather/WeatherBriefingTest.java
  batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/shortTermWeatherForecast/writer/WeatherWriter.java
  frontend/src/pages/homePage/desktop/components/workContainer/WorkContainer.tsx
  frontend/src/pages/loginPage/LoginPage.style.ts
  frontend/src/pages/loginPage/LoginPage.tsx
  frontend/src/pages/loginPage/hooks/useLogin.ts
  frontend/src/pages/weatherBoardPage/hooks/useWeatherQuery.ts
Labels: Release, 👥공통

#584 [Release] FrontEnd 1.0.8
  frontend/src/pages/homePage/desktop/components/damagePests/DamagePests.tsx
  frontend/src/pages/weatherBoardPage/hooks/useWeatherQuery.ts
Labels: 🖼️ FE, Release
